### ISSUE TITLE
Ceil on total cost calculation

### ISSUE THREAD

**Issue by moltam** [devanych/yii2-cart#3]
When the `CartItem` [calculates](https://github.com/devanych/yii2-cart/blob/b841dc14da8ee5b79fcd832b302b5a11b64156d1/CartItem.php#L58-L61) the total cost of the item, it applies a `ceil()` call. I don't think this is necessary, in fact this can cause issues, because the `getPrice()` and `getCost()` might return different values. This is a screenshot demonstrating this from our webshop:

![Screenshot_1](https://user-images.githubusercontent.com/4578365/65318109-5a217000-db9d-11e9-912e-41229ed95d0a.jpg)

Do you think that removing the `ceil()` call is a viable solution for this issue?

**Comment by devanych** [comment]
This is most likely because you store the price in the float type. If you were storing in an integer type, you wouldn't have this problem.

**Comment by moltam** [comment]
This is not about storage (the above example is simply displaying the prices of the items in the cart). The calculated total price should be float. In USA, UK, etc. a lot of goods cost float prices, e.g. 19.90, 29.90, and so on.

In the example above, if one product costs 44.90 GBP, than the total price should be also 44.90. When the quantity is 2, the total price 89.9, but the `CartItem` returns 90.

**Comment by devanych** [comment]
I understand that. I'm saying that when prices are stored as an integer, it is much easier to work with them and you exclude such problems. It is necessary to store not in dollars, and in cents, and at a conclusion to bring them to a necessary look.

Store in a database an integer 2990 (cents), when processed by the `ceil()` function, it will remain 2990, and in the time of the withdrawal: `2990 / 100 = 29.90`.

With regards to your situation, make a fork and remove the `ceil()` function.
