### ISSUE TITLE
session_start(): Unexpected end of serialized data

### ISSUE THREAD

**Issue by fabiananillo** [devanych/yii2-cart#4]
Hello, I'm having this issue when i'm adding a new product to the cart

![Screenshot_20190925_142756](https://user-images.githubusercontent.com/19267263/65633103-f7ffab00-dfa0-11e9-8533-83a0cc554125.png)
What should I do?

**Comment by devanych** [comment]
Hello. This is not an extension issue, as the extension works with the session component of the yii framework itself. This problem has already been raised, here in [this topic](https://github.com/yiisoft/yii2/issues/13400). Which version of Yii2 are you using? Try to upgrade.
