### ISSUE TITLE
getTotalCost as float

### ISSUE THREAD

**Issue by vAlmaraz** [devanych/yii2-cart#5]
The CartItem class accepts price as float, but when retrieving the total cost, the SimpleCalculator cast them as integer

**Comment by devanych** [comment]
It happens because `CartItem::getCost()` method uses function `ceil()`. In the database, the `productFieldPrice` can be a string, float or an integer, but will be returned as an integer. And it is much better to store prices in the database as an integer than a float.

**Comment by vAlmaraz** [comment]
Thanks Devanych!
In my case, I need to keep it as float.

In case someone needs a workaround:
- Create a FloatCalculator class implementing devanych\cart\calculators\CalculatorInterface
- Copy the methods from SimpleCalculator
- Replace $item->getCost() by $item->getPrice() in getCost method
- Remember to specify this new class in main.php as calculatorClass

**Comment by devanych** [comment]
Thanks, closing.
